echo 'y' | GENERATE_TIME_LIMIT=14400 GENERATE_THREADS=10 UNSOLVED_PUZZLE_FILE=puzzles1.txt bun start.ts
echo 'y' | GENERATE_TIME_LIMIT=14400 GENERATE_THREADS=10 UNSOLVED_PUZZLE_FILE=puzzles2.txt bun start.ts
echo 'y' | GENERATE_TIME_LIMIT=14400 GENERATE_THREADS=10 UNSOLVED_PUZZLE_FILE=puzzles3.txt bun start.ts
