name: PR Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: ${{ steps.get_redis_version.outputs.redis_image }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Get Redis image version from package.json
        id: get_redis_version
        run: |
          REDIS_IMAGE=$(jq -r .config.redisImage package.json)
          echo "redis_image=$REDIS_IMAGE" >> $GITHUB_ENV

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies with Bun
        run: bun install

      - name: Run tests
        id: test
        shell: bash
        run: |
          set -o pipefail
          bun tests.ts | tee test-output.txt
          grep -q '\[Clearinghouse\] ✅ Tests passed successfully!' test-output.txt

