name: PR Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies with Bun
        run: bun install

      - name: Run tests
        id: test
        shell: bash
        run: |
          set -o pipefail
          output=$(bun tests.ts | tee test-output.txt)
          echo "$output"
          echo "$output" | grep '\[Clearinghouse\] ✅ Tests passed successfully!'
